### ISSUE TITLE
Touchscreen issues

### ISSUE THREAD

**Issue by konrad11901** [konrad11901/Inspiron7373-macOS#2]
With current configuration, one finger works as a stylus, two fingers behave as one, three as two, four as three. That's pretty uncomfortable, to say at least.

Unfortunately, I don't know how to fix that, so any help is appreciated.

**Comment by baddles** [comment]
Can you try returning only ConcentratedTemplate(SBFB, SBFG) on TPL1 itself?

**Comment by konrad11901** [comment]
> Can you try returning only ConcentratedTemplate(SBFB, SBFG) on TPL1 itself?

Tried that, no improvement in my case.

By the way, it looks like it is a known issue (https://github.com/alexandred/VoodooI2C/issues/275, https://github.com/alexandred/VoodooI2C/issues/288), so I'd just wait for the VoodooI2C update.

**Comment by baddles** [comment]
Usually I use 2 fingers to scroll and one finger acts as a mouse click. It's fine for me, cuz that's how macOS work, since touch scrolling isn't a thing.

**Comment by konrad11901** [comment]
Oh, so you don't have to use three fingers in order to scroll? (that's how it works on my laptop...)

If scrolling requires only two fingers with your config, could you attach SSDTs and ACPI patches related to the I2C devices (touchscreen & touchpad) that you're using? Thanks!

**Comment by blankmac** [comment]
Fixed.  https://github.com/alexandred/VoodooI2C/pull/295

**Comment by baddles** [comment]
> Oh, so you don't have to use three fingers in order to scroll? (that's how it works on my laptop...)
> 
> If scrolling requires only two fingers with your config, could you attach SSDTs and ACPI patches related to the I2C devices (touchscreen & touchpad) that you're using? Thanks!

https://github.com/baddles/DELL-Inspiron-7373-CLOVER-EFI

This was the EFI that I use back then, note that this uses Clover and is quite messy, but it worked.

**Comment by konrad11901** [comment]
@blankmac Great, thanks a lot for your fix! I'll compile the kext shortly and if it works correctly, I'll include it in my repo.

@baddles Thanks for sharing your repo! I see that you were using VoodooI2C 2.2. The touchscreen issue came with VoodooInput integration, which was introduced in VoodooI2C 2.4. That probably explains the correct behaviour with your config.

**Comment by konrad11901** [comment]
Can confirm @blankmac's fixes work as expected. I'll upload the new kexts.
